### ISSUE TITLE
치노

### ISSUE THREAD

**Issue by ghostdeleted** [koreanbots/verification#11]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
|  치노   |  426722888293548032  |

Koreanbots 사이트 링크: https://koreanbots.dev/bots/426722888293548032

## 해당하는 기준

- [x] 700개 이상의 서버
- [x] 10만명 이상의 중복 유저
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇

### 봇 설명
사이트에 적어놨음
#### 봇 메인 컨텐츠 혹은 기능
뮤직

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?
4781서버 157538유저

#### 수집하는 개인정보는 무엇인가요?
에러 로그, 길드 아이디, 유저 아이디

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
about
#### 어느정도의 업타임을 기대할 수 있나요?
99.99999999999999999999999999999999999999999999999999
#### 어떤 저장방식을 이용하고 있나요?

저장 안해요
#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
chinobot.ga

#### 저희가 해당 봇을 신뢰해도될까요?
ㅇㅇ

**Comment by wonderlandpark** [comment]
수집하고 있는 개인정보가 어디에, 개인정보 약관을 확인할 수 있는공간을 알려주세요.

**Comment by ghostdeleted** [comment]
/home/ubuntu/chinobot/logs

**Comment by ghostdeleted** [comment]
약관 있는데요: https://policy.naver.com/policy/service.html

**Comment by wonderlandpark** [comment]
개인정보약관이 존재하지 않아 거부되었습니다.

**Comment by ghostdeleted** [comment]
만들어 오죠 딱대
