### ISSUE TITLE
치노봇

### ISSUE THREAD

**Issue by ghostdeleted** [koreanbots/verification#12]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
|치노|426722888293548032|

Koreanbots 사이트 링크: 
아이디 써놨어요

## 해당하는 기준

- [x] 700개 이상의 서버
- [x] 10만명 이상의 중복 유저
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇

### 봇 설명
뮤직봇
#### 봇 메인 컨텐츠 혹은 기능
뮤직

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?
총 유저수
157718
총 길드 수
4781

#### 수집하는 개인정보는 무엇인가요?
디코 아이디, 봇 설정
https://github.com/SiruBOT/Terms

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
https://github.com/SiruBOT/Terms
#### 어느정도의 업타임을 기대할 수 있나요?
99.00000000000000000000000000000000000000000000000000000000000000000001
#### 어떤 저장방식을 이용하고 있나요?

**J S O N**
#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
서포트 서버

#### 저희가 해당 봇을 신뢰해도될까요?
ㅇㅇ

**Comment by ghostdeleted** [comment]
승인 ㄱㄱ

**Comment by wonderlandpark** [comment]
JSON에 대한 보안은 확보가 되나요?

**Comment by ghostdeleted** [comment]
네 암호화되있어요

**Comment by sannoob** [comment]
세계제일 MD5

**Comment by wonderlandpark** [comment]
관리자 회의 후 통보드리겠습니다.

**Comment by sannoob** [comment]
회의 시작합시다

**Comment by wonderlandpark** [comment]
승인되었습니다.

**Comment by ghostdeleted** [comment]
✔️

**Comment by ReDesignedJP** [comment]
뭐하자는거야
