### ISSUE TITLE
전적이

### ISSUE THREAD

**Issue by en-you** [koreanbots/verification#14]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
|전적이|756792224099991622|

Koreanbots 사이트 링크: https://koreanbots.dev/bots/756792224099991622

## 해당하는 기준

- [x] 700개 이상의 서버
- [x] 10만명 이상의 중복 유저
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇

### 봇 설명
리그 오브 레전드, 레인보우 식스 시즈, 마인크래프트 하이픽셀 서버의 게임 전적을 확인하거나
디스코드 내에서 명령어로 도박, 주식 게임을 하거나 관리, 음악 기능을 사용할 수 있는 봇입니다.
#### 봇 메인 컨텐츠 혹은 기능
도박 및 주식 게임

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?
4,007 서버, 134,900명의 중복 유저

#### 수집하는 개인정보는 무엇인가요?
https://jeonjeok.com/privacy

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
개인정보를 수집하는 명령어 사용 전 이용약관 및 개인정보처리방침에 동의해야 사용할 수 있습니다.
(https://i.imgur.com/glGuex8.png)

#### 어느정도의 업타임을 기대할 수 있나요?
업데이트, 디스코드 봇 토큰 변경, 호스팅 장애를 제외하면 100%

#### 어떤 저장방식을 이용하고 있나요?

MongoDB, MariaDB, DynamoDB

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
서포트 서버 내 문의 티켓을 이용해서 소통할 수 있습니다.

#### 저희가 해당 봇을 신뢰해도될까요?
예

**Comment by wonderlandpark** [comment]
기존 승인된 적이 있던 봇(#3)으로 봇 계정이 변경되었지만, 서비스에는 변경된 점이 없으므로 내부회의 없이 자체적으로 승인합니다.

**Comment by wonderlandpark** [comment]
`인증된 봇` 권한이 부여된 후 닫도록 하겠습니다.
