### ISSUE TITLE
<FreeAI>

### ISSUE THREAD

**Issue by ZeroOneDeveloper** [koreanbots/verification#18]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
| FreeAI | 695899835953578025 |

Koreanbots 사이트 링크: https://koreanbots.dev/bots/695899835953578025

## 해당하는 기준

- [x] 1000개 이상의 서버
- [x] 10만명 이상의 중복 유저
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇

### 봇 설명
많은 봇들의 기능을 하나의 봇으로 통합한 봇입니다.

#### 봇 메인 컨텐츠 혹은 기능
게임 기능(주식, 경제 기능)

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?
현재 서버수 : 1375
현재 중복 유저수 : 인텐트때문에 알 수 없음(게임 서비스 가입 유저 수: 916)

#### 수집하는 개인정보는 무엇인가요?
유저들의 아이디를 수집합니다.

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
https://github.com/UniqueCodeGit/FreeAI_Tearms/

#### 어느정도의 업타임을 기대할 수 있나요?
99.9%

#### 어떤 저장방식을 이용하고 있나요?
MongoDB

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
문의 기능을 통해서 개발자에게 자신의 의견을 전달하거나, 개발자가 확인하여 답변하는 방식입니다.

#### 저희가 해당 봇을 신뢰해도될까요?
항상 신뢰 할수 있는 봇을 만들도록 노력하겠습니다.

**Comment by wonderlandpark** [comment]
가입 유저 수가 너무 적습니다. 추후에 다시 신청해주세요.
