### ISSUE TITLE
<노래하는하리보>

### ISSUE THREAD

**Issue by JellyBrick** [koreanbots/verification#19]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
|노래하는하리보|479108435984515072|

`Koreanbots` 사이트 링크: https://koreanbots.dev/bots/479108435984515072

## 해당하는 기준

- [x] 1000개 이상의 서버
- [x] 유저가 지원받을 수 있는 방법이 존재
- [ ] ~~수집하는 개인정보를 명시~~ (개인정보를 수집하지 않음 / **관련 기능 존재 X**)
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇

#### 봇 메인 컨텐츠 혹은 기능

디스코드 서버에 초대하여 노래를 들을 수 있는 봇입니다. 

#### 현재 서버 수와 중복 유저 수(혹은 가입 유저 수)는 어떻게되나요?

- `73732` 서버 (`2021/4/25` 기준)
- 중복 유저 수 측정 불가

#### 수집하는 개인정보는 무엇인가요?

**없습니다.**

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?

없습니다.

#### 어느정도의 업타임을 기대할 수 있나요?

- 99%+

#### 어떤 저장방식을 이용하고 있나요?

- MariaDB

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?

- [공식 서포트 서버](https://discord.gg/9cgYRC3)
- 관리자 DM

#### 저희가 해당 봇을 신뢰해도될까요?

넵

**Comment by zero734kr** [comment]
1. 공식 서포트 주소를 ``[공식 서포트 서버](https://discord.gg/초대)`` 형식으로 명시
2. 중복 유저 수 측정 불가의 뜻
  2-1. Intent가 없어서 측정 불가인지 또는 다른 외부 요인에 의해서인지
  2-2. 전자일 경우 운영하면서 캐시가 쌓일테니 유저 캐시에 잡힌 가장 큰 숫자를 입력 
3. 개인 정보 관련해서 없다고 하였으나 Intents를 승인 받은 경우 서술 

확인 후 답변 부탁드립니다.

**Comment by wonderlandpark** [comment]
수집하는 개인정보가 없다고 하셨는데 저장방식인 MariaDB에는 어떤 정보가 저장되나요?

**Comment by JellyBrick** [comment]
봇 설정이 저장됩니다.

**Comment by JellyBrick** [comment]
@zero734kr 
> 1. 공식 서포트 주소를 ``[공식 서포트 서버](https://discord.gg/초대)`` 형식으로 명시
> 2. 중복 유저 수 측정 불가의 뜻
>   2-1. Intent가 없어서 측정 불가인지 또는 다른 외부 요인에 의해서인지
>   2-2. 전자일 경우 운영하면서 캐시가 쌓일테니 유저 캐시에 잡힌 가장 큰 숫자를 입력 
> 3. 개인 정보 관련해서 없다고 하였으나 Intents를 승인 받은 경우 서술 
> 
> 확인 후 답변 부탁드립니다.

## 공식 서포트 서버 주소

- [공식 서포트 서버](https://discord.gg/9cgYRC3)

## 중복 유저 수 측정 불가 관련

- Intent를 승인받지 않았습니다.
- 현재 (`2021/4/27 PM 2:33`) 음성 채널 사용 중인 유저 수만 집계 (`23750`명)


## Intent를 승인받지 않았음

**Comment by wonderlandpark** [comment]
승인되었습니다. 축하드립니다

이슈는 뱃지 추가 후 닫도록 하겠습니다.
