### ISSUE TITLE
한마루

### ISSUE THREAD

**Issue by seojin200403** [koreanbots/verification#20]
# 인증 신청

## 봇 설명
| 봇 이름 | 봇 ID | 
|--------|-------|
|한마루|686460052982464522|

Koreanbots 사이트 링크: https://koreanbots.dev/bots/686460052982464522

## 해당하는 기준
- [x] 1000개 이상의 서버
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇
### 봇 설명
귀여운 미니게임 봇 한마루입니다. 
#### 봇 메인 컨텐츠 혹은 기능
미니게임(슬롯머신, 블랙잭, 바카라, 끝말잇기, 요트 다이스)
#### 현재 서버 수와 중복 유저 수(혹은 가입 유저 수)는 어떻게되나요?
- 서버: `1100`곳
- 중복 유저: 약 `33,300`명
(2021-05-07 기준)
#### 수집하는 개인정보는 무엇인가요?
봇 이용자(이름, 식별자, id), 봇 이용 메시지(내용, 시간)
#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
[koreanbots 봇 페이지](https://koreanbots.dev/bots/686460052982464522), [초대 링크](https://discord.com/api/oauth2/authorize?client_id=686460052982464522&permissions=70773969&scope=bot%20applications.commands)에서의 개인정보보호정책에 명시되어 있습니다. 
#### 어느정도의 업타임을 기대할 수 있나요?
95% 이상
#### 어떤 저장방식을 이용하고 있나요?
MariaDB
#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
봇에 명시되어 있는 지원 서버에 참가하여 메시지를 보내거나, 약관에 명시된 개발자의 이메일을 통해 소통할 수 있습니다.
#### 저희가 해당 봇을 신뢰해도될까요?
ㅔ

**Comment by wonderlandpark** [comment]
아쉽지만 이번 기회에는 승인이 어려울거 같습니다.
서버별 평균 유저 수가 너무 적습니다. 따라서 조건에 만족한다고 판단하기에 어려움이 있습니다.
