### ISSUE TITLE
FreeAI

### ISSUE THREAD

**Issue by ZeroOneDeveloper** [koreanbots/verification#21]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
| FreeAI | 695899835953578025 |

Koreanbots 사이트 링크: https://koreanbots.dev/bots/695899835953578025

## 해당하는 기준

- [X] 1000개 이상의 서버
- [X] 유저가 지원받을 수 있는 방법이 존재
- [X] 수집하는 개인정보를 명시
- [X] 평균 90퍼센트 이상의 업타임
- [X] 안전하고 신뢰할 수 있는 저장방식
- [X] 디스코드 인증된 봇

### 봇 설명
- 여러 봇들의 기능들을 한 봇에 모아놓은 다기능 챗봇입니다.

#### 봇 메인 컨텐츠 혹은 기능
- 메인 컨텐츠로는 게임(경제) 기능이 있습니다!

#### 현재 서버 수와 중복 유저 수(혹은 가입 유저 수)는 어떻게되나요?
- 2021년 5월 10일 오전 9시 23분 기준 `1880` 서버
- 인텐트로 인해 측정 불가

#### 수집하는 개인정보는 무엇인가요?
- 유저의 아이디

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
- https://github.com/UniqueCodeGit/UniqueCode_Terms

#### 어느정도의 업타임을 기대할 수 있나요?
- 99%+

#### 어떤 저장방식을 이용하고 있나요?

- MongoDB

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
- 문의 기능, 서포트 서버 질문 채널

#### 저희가 해당 봇을 신뢰해도될까요?
넵

**Comment by wonderlandpark** [comment]
봇의 실규모를 파악하는데 어려움이 있습니다. 가입 유저 수 등을 기재부탁드립니다.

**Comment by ZeroOneDeveloper** [comment]
인증된봇 인텐트 신청 개념이 생기기 이전 기록을 참고해보니,
중복 유저 112277명, 게임 유저 가입자수 2244명으로 조회되었습니다.
따라서 지금은 더 많을것으로 예상됩니다.

**Comment by wonderlandpark** [comment]
인텐트가 없더라도 봇을 키면 길드에 memberCount가 주어집니다. 이로 계산 부탁드립니다.

**Comment by ZeroOneDeveloper** [comment]
맞는지 정확히 몰라, 코드도 같이 남겨봅니다.
```py
num = 0
for i in bot.guilds:
    num += i.member_count
```
num을 출력했을때, `57737` 로 조회되었습니다.

**Comment by wonderlandpark** [comment]
서버 수 대비 유저 수가 적은 것 같습니다. 아쉽지만 이번에는 승인하기에는 어려워보입니다. 다음을 기약해봅시다!
