### ISSUE TITLE
끝봇 인증 신청 

### ISSUE THREAD

**Issue by janu8ry** [koreanbots/verification#25]
### 봇 이름

끝봇

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/703956235900420226

### 봇 소개

끝봇은 끝말잇기가 주 기능인 인증된 디스코드 봇입니다.
봇과의 1 대 1 끝말잇기 대결, 서버원들과의 다인전 게임 등을 플레이 할 수 있습니다.

### 봇의 서버 및 유저 수

서버: 5298개 / 중복 유저: 140056명

### 수집하는 개인정보

봇 이용자, 봇 이용 서버/채널, 봇 이용 메시지(커맨드 사용 로그)

### 개인정보에 관한 안내

https://github.com/janu8ry/kkutbot/blob/main/privacy.md
위 링크에 자세하게 안내되어 있습니다.

### 업타임

95%

### 호스팅

라즈베리파이와 오라클 a1

### 저장방식

mongoDB

### 유저 소통 방법

서포트 서버: https://discord.gg/z8tRzwf

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by wonderlandpark** [comment]
호스팅하고 계신 곳이 라즈베리파이라고 작성해주셨는데 그러면 홈 서버에서 호스팅되는건가요? 어떤식 보안장치가 있는지도 설명해주실 수 있나요?

**Comment by janu8ry** [comment]
> 호스팅하고 계신 곳이 라즈베리파이라고 작성해주셨는데 그러면 홈 서버에서 호스팅되는건가요? 어떤식 보안장치가 있는지도 설명해주실 수 있나요?

봇, mongoDB는 홈서버(라즈베리파이) 에서 돌아가고 있고 가끔씩 오라클 클라우드로 돌아가고 있습니다.
홈서버는 공유기 방화벽을 열어놓지 않아서 로컬에서만 접근이 가능하고, 인증키 방식으로만 ssh 연결이 가능합니다.

**Comment by wonderlandpark** [comment]
가끔씩 돌아간다는 데이터베이스의 위치가 바뀌는건가요?

**Comment by wonderlandpark** [comment]
봇에 유저가 확인할 수 있는 부분에 따로 개인정보취급방침이 명시되어있지 않은 것으로 보입니다.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/31924512/131300786-757aaf05-97be-4779-a455-45c74f1ecb3e.png">

**Comment by janu8ry** [comment]
> 봇에 유저가 확인할 수 있는 부분에 따로 개인정보취급방침이 명시되어있지 않은 것으로 보입니다.
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/31924512/131300786-757aaf05-97be-4779-a455-45c74f1ecb3e.png">

<img width="396" alt="Screen Shot 2021-08-30 at 4 29 09 PM" src="https://user-images.githubusercontent.com/68150356/131302399-b421679b-a125-4cd2-a7bd-4b240b419cbc.png">
봇 초대 화면에서 확인가능합니다.

**Comment by wonderlandpark** [comment]
봇에 기재해주세요. 이의 제기를 기각합니다.
