### ISSUE TITLE
투표 봇

### ISSUE THREAD

**Issue by kimdonut** [koreanbots/verification#27]
### 봇 이름

투표

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/582903352946327552

### 봇 소개

# 투표
간단한 명령어로 투표를 쉽게 만들 수 있습니다.

## 기능

- 투표
- 로그/관리
- 유틸리티

### 봇의 서버 및 유저 수

서버: 12,212개 / 유저: 526,268명의 중복 유저

### 수집하는 개인정보

https://gajae.kr/#/privacy
- 봇을 초대한 서버의 정보 (서버 ID, 선택)
- 봇을 사용한 유저의 정보 (유저 ID)
- 이메일 주소 (선택)

선택 항목은 사용하는 명령어에 따라 상이함. 또한 봇 초대 시 바로 정보를 수집하는 것이 아닌, 봇 명령어 사용 시 수집됨.

### 개인정보에 관한 안내

봇 내 `=명령어` 명령어와 [봇 초대 화면](https://discord.com/oauth2/authorize?client_id=582903352946327552&scope=bot+applications.commands&permissions=387144&response_type=code&redirect_uri=https://gajae.kr/discord), [공식 서버](https://discord.gg/XNP7tR5) `#규칙` 채널에서 안내합니다. 기본적으로 봇 초대 및 봇 이용 시 [개인정보 처리 방침](https://gajae.kr/#/privacy)에 동의하게 됩니다.

### 업타임

97%

### 호스팅

오라클 클라우드

### 저장방식

MySQL, SQLite

### 유저 소통 방법

[공식 서버](https://discord.gg/XNP7tR5)와 메일 (me@gajae.kr)

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by wonderlandpark** [comment]
승인되었습니다. 축하드립니다 🎉 

이슈는 뱃지 추가 후 닫도록 하겠습니다.
