### ISSUE TITLE
lofi girl v2

### ISSUE THREAD

**Issue by pmh-only** [koreanbots/verification#28]
### 봇 이름
lofi girl v2
<br />

### 한국 디스코드 리스트 봇 URL
https://koreanbots.dev/bots/763033945767280650
<br />

### 봇 소개
<image align="right" src="https://camo.koreanbots.dev/6d0fd795b6f565cbc284b7fe49beccdca8691543/68747470733a2f2f656f64692e67612f684d5551666d36793367" width="300" />

1. 이 봇은 명령어를 손수 입력해야 하는 기존 음악봇들의 단점을 해결한 봇 입니다.
2. 음악을 재생할때 명령어를 통해 음악을 검색하는 것이 아니라, 사용자가 정해진 음성 채널에 들어오면 정해진 음악을 재생합니다.
3. 모든 사용자가 음성 채널에서 떠나면 자원 보호를 위해 봇도 재생을 종료합니다.
4. 위와 같은 특징이 있어 같은 노래를 연속적으로 트는 스터디 그룹이나 휴식하는 채널 같은데 쓰면 좋습니다.

<br />

### 봇의 서버 및 유저 수
서버: 6361개 / 중복 유저: 279069명
<br />

### 수집하는 개인정보
저희 서비스는 원할한 서비스 제공을 위해 다음과 같은 개인정보를 수집합니다.

- **사용자식별번호**
`Discord`측에서 발급한 사용자 고유 식별번호를 사용자 식별을 위해 수집합니다.
<br />

### 개인정보에 관한 안내
저희 서비스는 사용자의 개인정보 보호를 위해 다음과 같이 안내하고 있습니다.

- **개인정보취급방침**
개인정보취급방침은 [이곳](https://lofi.pmh.codes/)에서 확인하실 수 있습니다.\
해당 링크는 봇 초대시 보이는 `oauth` 화면에 표시됩니다.\
또한 봇 내부 `/help` 명령을 통해 확인할 수 있습니다.

- **제 3자 위탁 업체 안내**
본 서비스는 제 3자 위탁 업체를 이용하지 않습니다.
<br />

### 업타임
97% 이상
<br />

### 호스팅
Microservices, HA 아키텍쳐로 구성된 Oracle Cloud (arm)
<br />

### 저장방식
MariaDB (MySQL)
<br />

### 유저 소통 방법
저희 서비스는 사용자의 이용 편의를 위해 다음과 같이 사용자와 소통하고 있습니다.

- **지원서버**
https://discord.gg/WJRtvankkB
위 서버에서 사용자들의 대한 질문, 기능건의, 버그신고 등을 받고 있습니다.\
해당 서버 초대 링크는 봇의 `/help` 명령을 통해 확인 할 수 있습니다.

- **이메일**
mailto:pmhstudio.pmh@gmail.com
지원서버를 통한 지원이 힘들경우 이메일을 통해 지원받을 수 있습니다.
<br />

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by wonderlandpark** [comment]
승인되었습니다. 축하드립니다 🎉 

이슈는 뱃지 추가 후 닫도록 하겠습니다.

**Comment by pmh-only** [comment]
역대 가장 빠른 처리 속도 상을 받으셨습니다. 축하드립니다 :tada:

앞으로는 더 신속하게 처리되었으면 하는 바람입니다 :wink:

**Comment by wonderlandpark** [comment]
추가로 확인해야하는 사항이 있어 승인을 잠시 보류하도록 하겠습니다.

오래 기다리시게 한 점은 진심으로 사과드립니다.

**Comment by pmh-only** [comment]
앗, 네넵 

어떤 이유인진 모르겠지만 내부 규정에 따라 진행된 걸로 생각하겠습니다.

시간은 얼마든지 쓰셔도 됩니다 :smile:

**Comment by wonderlandpark** [comment]
카테고리에 `빗금 명령어` 명시 부탁드립니다.

추가로, 이슈 설명에 적어주신 봇 소개를 경어체로 수정해주셨으면 함니다.

**Comment by wonderlandpark** [comment]
안녕하세요, 말씀해주신 내용에 착오가 있어 수정드립니다. 확인 결과 첨부해주신 사진은 저희 한디리 내부 채팅이 아닙니다. 대화의 출처를 잘 모르겠습니다.

또한, 말씀드린 내용은 이해가 어렵다는 것이 아닌 봇 소개가 경어체로 작성되지 않아 수정 요청드린 것입니다. 말씀드린 내용과 논점이 다른 내용 같습니다.

**Comment by pmh-only** [comment]
음~ 그렇군요.

일단 알겠습니다. 제가 개인적인 착오가 있었던것 같네요.

이슈 내용을 성실히 적었으나, 출처를 알 수 없는 사진의 내용을 읽은 후로 감정이 상해 경어체를 사용하지 않았던 거 같습니다. 불편하셨다면 이 점에 대하여 죄송하다는 말씀을 드립니다..

**Comment by wonderlandpark** [comment]
승인되었습니다. 축하드립니다 🎉

이슈는 뱃지 추가 후 닫도록 하겠습니다.
