### ISSUE TITLE
뽀삐 봇

### ISSUE THREAD

**Issue by siy-uuu** [koreanbots/verification#32]
### 봇 이름

뽀삐

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/896270994740764684

### 봇 소개

메인 기능은 음악이며 이외에 도박, 전적, 유틸리티등 다양한 기능이 있는 봇 입니다

### 봇의 서버 및 유저 수

서버: 6556개

### 수집하는 개인정보

유저 정보, 서버 정보 등등의 개인정보를 수집하며 아래 개인정보 처리 방침에서 자세하게 보실 수 있습니다!

https://github.com/NEXT1122/POPPY/blob/main/뽀삐%20개인정보처리방침.md

### 개인정보에 관한 안내

제4조 (개인정보의 파기절차 및 파기방법)
파기절차
1. 서포트 서버 방문
2. 사용자의 개인 데이터 파기 요청
3. 사용자의 데이터 파기

파기방법
1. 전자적 파일 형태의 정보는 기록을 재생할 수 없는 기술적 방법을 사용합니다

[https://github.com/NEXT1122/POPPY/blob/main/뽀삐%20개인정보처리방침.md](https://github.com/NEXT1122/POPPY/blob/main/%EB%BD%80%EC%82%90%20%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%EC%B2%98%EB%A6%AC%EB%B0%A9%EC%B9%A8.md#%EC%A0%9C4%EC%A1%B0-%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%EC%9D%98-%ED%8C%8C%EA%B8%B0%EC%A0%88%EC%B0%A8-%EB%B0%8F-%ED%8C%8C%EA%B8%B0%EB%B0%A9%EB%B2%95)

### 업타임

99%

### 호스팅

GalaxyGate

### 저장방식

MongoDB

### 유저 소통 방법

서포트 서버와 이메일 등으로 소통 & 질문 할 수 있습니다!

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [x] f. 디스코드 인증된 봇

**Comment by eunwoo1104** [comment]
다음 내용을 확인 부탁드립니다.

가. 개인정보처리방침 제6조에 관련해서, 말씀하신 ‘쿠키 (Cookie)'는 웹 관련 기술로 디스코드 봇과 상관이 없는 것으로 확인됩니다. 귀 서비스의 상표를 사용해 웹사이트를 운영한 사실이 있으신가요? 만약 없다면, 디스코드 봇과 이용자가 상호작용하는 과정에서 제3자가 개인정보를 수집하는 경우 해당 서비스의 이름을 기술 부탁드립니다.

나. 개인정보처리방침 문서상 마지막 발효 시기는 2021년 10월 9일로 확인되는데, 해당 레포지토리의 커밋 기록을 확인 결과 첫 커밋 날짜가 2022년 11월 1일로 확인되며 초대 링크의 Privacy Policy 링크 또한 해당 레포지토리임이 확인됩니다. 해당 깃헙 레포지토리로 공식 문서를 안내하기 전 어떤 방법을 사용하여 개인정보처리방침을 안내하셨는지 알 수 있을까요? 

다. 개인정보처리방침의 변동 사항이 생길 경우, 사용자 권익을 위하여 실제 발효가 생기기 전 유예 기간을 두어 이용자에게 안내하는 것이 사회 보편적인 방법이라고 생각됩니다. 귀 서비스의 문서에서는 해당 조항이 누락된 이유를 알 수 있을까요?

**Comment by siy-uuu** [comment]
가: 현재 뽀삐 [웹사이트](https://discordmusic.xyz)가 있습니다.
나: 구글 사이트 도구를 사용해 사이트를 만들어 개인정보 처리 방침을 안내하고 있었습니다. 현재 github으로 새롭게 만들어 이전했습니다. (이전 구글 사이트는 삭제 해버렸습니다.)
다: 잘 몰랐었습니다. 수정 완료했습니다.

**Comment by eunwoo1104** [comment]
추가로, 봇이 사용자와 상호 작용할 때 어떤 개인정보를 수집하는지 알 수 있을까요? 또한, 제3자 서비스를 사용하기 위해 사용자의 개인정보를 제공하신 사실이 있으신가요? 만약 있으시다면 어떤 서비스를 사용하고 계신가요? (예: sentry 등)

**Comment by siy-uuu** [comment]
봇이 사용자와 상호 작용할 때 유저 정보(디스코드 닉네임, 디스코드 아이디, 디스코드 프로필 사진)을 수집합니다. 
사용자의 개인정보를 제공한 적이 없습니다.

**Comment by eunwoo1104** [comment]
인증 심사 중 디스코드 인증을 받기 위해 ToS에 위반되는 기능을 우회해 인증을 받은 것이 확인되었습니다. 이에 해당 봇에 대한 신뢰도가 부족하다고 판단해 거부 처리되었습니다.
