### ISSUE TITLE
EX

### ISSUE THREAD

**Issue by minchan304** [koreanbots/verification#33]
### 봇 이름

EX

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/931152690636017704

### 봇 소개

<mark>도박</mark>을 중심으로 한 봇이며, 관리, 음악 기능이 추가적으로 있습니다.

### 봇의 서버 및 유저 수

서버: 5008 

### 수집하는 개인정보

사용자의 디스코드 아이디, 채널 아이디, 서버 아이디를 수집합니다. 
수집하는 명령어:
/개인음성채널, /복권 구매, /출석, /인증설정

### 개인정보에 관한 안내

[깃허브](https://github.com/minchan304/EX-Bot/blob/main/개인정보처리방침.md) 또는 봇 초대 화면, 도움말 명령어에서 확인하실 수 있습니다.

파기방법 
사용자는 /데이터 삭제 명령어를 통해 데이터를 삭제할 수 있으며 되돌릴 수 없습니다.
도박 데이터의 경우 서포트 서버로 방문 후 문의하시면 삭제가 가능하며 되돌릴 수 없습니다.

### 업타임

99.8%

### 호스팅

가상 호스팅 (픽스)

### 저장방식

몽고 DB

### 유저 소통 방법

서포트 서버로 방문 후 티켓 또는 자유채팅으로 문의할 수 있으며, 사이트 내부에 문의 기능이 존재하며 이메일로도 문의가 가능합니다.

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by eunwoo1104** [comment]
안녕하세요, 내부 사정으로 해당 인증봇 신청을 뒤늦게 확인했습니다.
인증봇 심사가 크게 지연된 점에 대해 사과드리며, 최대한 빠른 시간 안에 인증 절차를 마무리하도록 하겠습니다.

**Comment by eunwoo1104** [comment]
심사 진행 도중 기존의 비정상적인 수의 API 요청 기록으로 당사는 귀하의 봇을 신뢰할 수 없다고 판단하였습니다. 이에 해당 신청건은 거부 처리되었습니다.
