### ISSUE TITLE
끝봇

### ISSUE THREAD

**Issue by janu8ry** [koreanbots/verification#34]
### 봇 이름

끝봇

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/703956235900420226

### 봇 소개

끝봇은 끝말잇기가 주 기능인 인증된 디스코드 봇입니다.
봇과의 1 대 1 끝말잇기 대결, 서버원들과의 다인전 게임 등을 플레이 할 수 있습니다.

### 봇의 서버 및 유저 수

서버: 9602개 / (중복/가입) 유저: 367648명

### 수집하는 개인정보

봇 이용자, 봇 이용 서버/채널, 봇 이용 메시지(커맨드 사용 로그)

### 개인정보에 관한 안내

https://github.com/janu8ry/kkutbot/blob/main/privacy.md
위 링크에 자세하게 안내되어 있고,
봇의 도움말 명령어 사용시 위 링크가 기제되어 있습니다.

### 업타임

95% 이상

### 호스팅

Oracle A1

### 저장방식

MongoDB

### 유저 소통 방법

[서포트 서버](https://discord.gg/z8tRzwf)와 이메일을 통해 소통할 수 있습니다.

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by eunwoo1104** [comment]
승인 축하드립니다! 🎉
해당 이슈는 신뢰된 봇 승인 절차 완료 후 닫도록 하겠습니다.
