### ISSUE TITLE
배틀이

### ISSUE THREAD

**Issue by kiss8981** [koreanbots/verification#35]
### 봇 이름

배틀이

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/928523914890608671

### 봇 소개

배틀이는 서버 관리를 주로 서비스 중인 봇 입니다
주요 기능은 서버를 웹 대시보드를 이용하여 관리하고 다양한 보안 관련 기능으로 서버를 보호할 수 있습니다.

### 봇의 서버 및 유저 수

서버: 7,135개 / (중복/가입) 유저: 389,322명

### 수집하는 개인정보

봇 이용자, 봇 이용 서버/채널, 서버 사용자 및 서버별 개인설정

### 개인정보에 관한 안내

https://battlebot.kr/privacy
위 링크에 자세하게 안내되어 있습니다

### 업타임

97%

### 호스팅

Oracle Cloud

### 저장방식

MongoDB

### 유저 소통 방법

[서포트 서버](https://discord.gg/WtGq7D7BZm)와 이메일, 웹 사이트 상담채팅을 통해 소통할 수 있습니다.

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by eunwoo1104** [comment]
최근 있었던 라이선스 관련 사건으로 당사는 귀하의 봇을 아직 신뢰할 수 없다고 판단하였습니다. 이에 해당 신청건은 거부 처리되었습니다.
