### ISSUE TITLE
Manbo

### ISSUE THREAD

**Issue by Jam-Manbo** [koreanbots/verification#36]
### 봇 이름

Manbo

### 한국 디스코드 리스트 봇 URL

https://koreanbots.dev/bots/846770591231246336

### 봇 소개

많은 기능을 지원하는 디스코드 봇입니다.
기능으로는 
- 상황에 따라 적재적소로 쓰일 수 있는 멤버 관리 기능
- 사용자의 활동량에 따른 레벨링 시스템
- 사용자 정보, 서버 정보 등 다양한 정보/스탯 확인
- 이모지를 이용한 역할 주고받기가 가능한 reaction role 시스템
- 원하는 대로 태그에 내용을 저장하여 사용할 수 있는 태그 시스템
- 계산기, 틱택토 등을 즐기고 사용할 수 있는 유틸리티
- 서버의 관리 기능 (초대링크/악성 링크 감지, 접두사 및 언어 변경)
- 여러가지 이미지 관련 기능들 (네코, blurpify, 마인크래프트 업적 등)
- 한정되어 있지만 마인크래프트 서버의 스탯 확인
- 출석체크와 가위바위보 등을 통한 가상 화폐 시스템
등이 있습니다.

### 봇의 서버 및 유저 수

서버: 7200개 / (중복/가입) 유저: 418000명

### 수집하는 개인정보

- 봇을 초대한 서버 정보 (서버 아이디, 봇 설정 - 접두사, 언어 등)
- 봇을 이용하는 사용자 정보 (사용자 아이디)
- (선택) 사용자가 들어가있는 서버 정보 (OAuth를 이용하여 추가적인 로그인을 할 경우)

### 개인정보에 관한 안내

해당 [링크](https://github.com/Team-Manbo/policy-tos)에서 확인 가능하며,
봇 명령어의 `/help` (슬래시 명령어) 혹은 `(길드별 접두사)help` (메세지 명령어)를 사용할 경우 링크가 게재되어 있습니다.
또한, 봇 초대 화면의 개인정보 처리 방침과 이용 약관에서도 확인 가능합니다.

### 업타임

100% (지난 6개월 22일 동안)

### 호스팅

OCI

### 저장방식

PostgreSQL, MongoDB, Redis

### 유저 소통 방법

[공식 지원 서버](https://discord.gg/YyJHW8QUS7)  및 개발자 [이메일](manboqt@gmail.com)
공식 지원 서버의 지원 채널을 사용하거나, 민감한 내용 등일 경우 티켓을 통해 지원을 받을 수 있습니다.

### 해당하는 기준

- [X] a. 5000개 이상의 서버
- [X] b. 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
- [X] c. 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시
- [X] d. 평균 95퍼센트 이상의 업타임
- [X] e. 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식, 호스팅 사
- [X] f. 디스코드 인증된 봇

**Comment by eunwoo1104** [comment]
개인정보 처리방침과 이용약관 문서가 어제 생성된 것으로 확인되는데, 이전에 어떤 방법으로 이 내용들을 안내하셨는지 확인할 수 있을까요?

**Comment by Jam-Manbo** [comment]
> 개인정보 처리방침과 이용약관 문서가 어제 생성된 것으로 확인되는데, 이전에 어떤 방법으로 이 내용들을 안내하셨는지 확인할 수 있을까요?

이전에 웹사이트 https://snorlax.me/policy 와 https://snorlax.me/tos 를 통해 안내했었습니다. 도메인이 만료되어 해당 내용을 깃허브로 옮겼습니다.

**Comment by eunwoo1104** [comment]
승인 축하드립니다! 🎉
해당 이슈는 신뢰된 봇 승인 절차 완료 후 닫도록 하겠습니다.
