### ISSUE TITLE
매리봇

### ISSUE THREAD

**Issue by kijk2869** [koreanbots/verification#4]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID |
|--------|-------|
|      매리봇      |      415401437246521344    |

Koreanbots 사이트 링크: https://koreanbots.cf/bots/415401437246521344

## 해당하는 기준

- [x] 10만명 이상의 중복 유저
- [ ] 1000개 이상의 서버
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식

### 봇 설명
온라인 라이브큐와 크로스페이드 등이 있는 다기능봇

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?
346서버 122504유저

#### 수집하는 개인정보는 무엇인가요?
무

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
필요 없음

#### 어느정도의 업타임을 기대할 수 있나요?
     .
99.9%

#### 어떤 저장방식을 이용하고 있나요?

MariaDB 

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
봇 DM 혹은 개발자 DM

**Comment by wonderlandpark** [comment]
어떠한 개인정보도 수집하지 않으신다면 기본적인 명령어 로깅도 제외되는건가요? 그러하면, DB에 저장되는 정보는 어떠한 것들인가요?

**Comment by kijk2869** [comment]
명령어 로그 또한 기록되지 않음
SQL쿼리만 오류 대응을 위해 로깅
명령어 사용시 파라미터 중 일부만 DB 저장

**Comment by wonderlandpark** [comment]
Approved. Will be added.

**Comment by wonderlandpark** [comment]
Closing issue when the badge is added
