### ISSUE TITLE
Spectre

### ISSUE THREAD

**Issue by ArdanKR** [koreanbots/verification#7]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID |
|------------|----------|
Spectre | 695639626752458762|

Koreanbots 사이트 링크: 
https://koreanbots.cf/bots/695639626752458762

## 해당하는 기준

- [ ] 1000개 이상의 서버
- [X] 10만명 이상의 중복 유저
- [X] 유저가 지원받을 수 있는 방법이 존재
- [X] 수집하는 개인정보를 명시
- [X] 평균 90퍼센트 이상의 업타임
- [X] 안전하고 신뢰할 수 있는 저장방식

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?

서버수: 39 (미달)
중복 유저 수: 102610 (충족)

#### 수집하는 개인정보는 무엇인가요?

https://github.com/ArdanK0R/Spectre_Document/blob/master/Privacy.md

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?

최초 가입시 문서 URL 전송

#### 어느정도의 업타임을 기대할 수 있나요?

개발중이 아니라면 거의 24시간 입니다.

#### 어떤 저장방식을 이용하고 있나요?

MongoDB

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?

서포트 서버, 이메일

**Comment by wonderlandpark** [comment]
조건은 만족하지만 서버 수가 원래 기준(1000서버)에 너무 차이가 큰듯합니다. 유저 수는 DBL등 외국 서버를 감안해야하고요. 아쉽게도 수락해드릴 수 없습니다.
