### ISSUE TITLE
Kal'tsit-Bot

### ISSUE THREAD

**Issue by frin0911** [koreanbots/verification#9]
# 인증 신청

## 봇 설명

| 봇 이름 | 봇 ID | 
|--------|-------|
|Kal'tsit-Bot|621013224610988042|

Koreanbots 사이트 링크: https://koreanbots.dev/bots/621013224610988042

## 해당하는 기준

- [x] 700개 이상의 서버
- [x] 10만명 이상의 중복 유저
- [x] 유저가 지원받을 수 있는 방법이 존재
- [x] 수집하는 개인정보를 명시
- [x] 평균 90퍼센트 이상의 업타임
- [x] 안전하고 신뢰할 수 있는 저장방식
- [x] 디스코드 인증된 봇

### 봇 설명
한국어와 영어를 모두 지원하는 디스코드 명일방주 전용 게임 챗봇입니다.
#### 봇 메인 컨텐츠 혹은 기능
명일방주 정보 제공, 서버 관리, 놀이

#### 현재 서버 수와 중복 유저 수는 어떻게되나요?
KST 2020-05-19 14:21 기준 서버 개수 833개, 유저 수 101,243명입니다.

#### 수집하는 개인정보는 무엇인가요?
언어, 로그 채널 설정 시 DB에 저장하는 채널 아이디
수집되는 개인정보는 디스코드 봇 인증 단계에서 명시 후 인증을 받은 내용이기에 별다른 문제는 없으리라 생각됩니다.

또한, 명령어 사용 시 오류가 발생하는 경우에는 해당 메시지의 내용을 개발자에게 전달함으로써 어떤 명령어에서 어떤 오류가 났는지 확인할 수 있게 설정하였습니다.

#### 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요?
한국 디스코드 봇 웹사이트 설명란에 기재되어 있습니다.

#### 어느정도의 업타임을 기대할 수 있나요?
기본적으로는 24시간 구동중이며, 재연결 시 5~10초 내외로 명령어 사용이 지연되는 일이 있으나, 
90퍼센트 이상의 업타임을 기대할 수 있을 것 같습니다.

#### 어떤 저장방식을 이용하고 있나요?

SQLite 이용중입니다.

#### 유저는 어떤 방법으로 개발자와 소통할 수 있나요?
지원 서버, 전용 이메일, 커뮤니티 홍보 글의 댓글 등으로 소통할 수 있습니다.

#### 저희가 해당 봇을 신뢰해도될까요?
네. 디스코드에서도 인증된 봇입니다.

**Comment by wonderlandpark** [comment]
인증 조건 변경으로 **하나의 메인 컨텐츠**가 존재해야합니다.

예) **뮤직**봇, **로깅**봇, **관리**봇, **검색**봇
